import { Home } from "./Home";
import  VotePanel from '../containers/VotePanelContainer';
import { Teamup } from './Teamup';
import { Signup } from './Signup';
import { Views } from './views';
import { Queries } from './Query';
import  Member  from '../containers/MemberContainer';
import { Schedule } from './Schedule';
import { Tinder } from './Tinder';
import { Login } from './Login';
export { Home };
export { VotePanel };
export { Teamup };
export { Views };
export { Queries };
export { Member };
export { Schedule };
export { Tinder };
export { Login };
export { Signup };